### ISSUE TITLE
Code coverage support 

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/kubernetes#15]
##### SUMMARY

One ansible-minimal is working again.
* Copy what grafana has for code coverage 
* generate codecov.io token 
* Enable Codecov commenting on PRs 

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by geerlingguy** [comment]
@gundalow - I have a draft PR up now that tests are passing again; see https://github.com/ansible-collections/kubernetes/pull/19

How can I get a token for this repository from codecov.io? Do I just ask you?
