### ISSUE TITLE
Test with Molecule 3.0 alpha

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/kubernetes#30]
##### SUMMARY

Molecule 3 will be a bit of a rearchitecture, which means some things are going, and some things are changing. We are using the `delegated` provider for KinD (for now, at least), which should work fine with Molecule 3. See the [Molecule 3 migration checklist](https://github.com/ansible-community/molecule/issues/2560) and [Molecule 3 changelog PR](https://github.com/ansible-community/molecule/pull/2562) for details.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

CI - Molecule tests

##### ADDITIONAL INFORMATION

N/A

**Comment by ssbarnea** [comment]
Please do! I am eager to get some feedback before adding the tag. Is called alpha but is more of a rc. Unless someone identifies a serious bug this will be the release.

**Comment by geerlingguy** [comment]
@ssbarnea - looks like it worked without issue, following your migration checklist.
