### ISSUE TITLE
No release 0.10 declared on github

### ISSUE THREAD

**Issue by bmillemathias-1a** [ansible-collections/kubernetes#75]
##### SUMMARY
https://github.com/ansible-collections/kubernetes/releases does not list lastest release.

##### ISSUE TYPE
- Bug Report

**Comment by geerlingguy** [comment]
Yikes! Thanks for catching that; I've added: https://github.com/ansible-collections/kubernetes/releases/tag/0.10.0

This will hopefully someday be impossible to have happen again once https://github.com/ansible-collections/kubernetes/issues/43 is solved, until then I'll try to be more diligent about pushing tags up to origin when I build and release the collection.

**Comment by bmillemathias-1a** [comment]
thanks !
